DROP TABLE IF EXISTS CAPITALS;
DROP TABLE IF EXISTS CITIES;

CREATE TABLE CITIES(
    NAME    TEXT,
    POPULATION  REAL,
    ELEVATION INT
);

CREATE TABLE CAPITALS(
    STATE   CHAR(2)
) INHERITS(CITIES);

INSERT INTO CITIES(NAME,POPULATION,ELEVATION) VALUES('HELLO',1000,100);
INSERT INTO CITIES(NAME,POPULATION,ELEVATION) VALUES('HELLO',2000,100);
INSERT INTO CITIES(NAME,POPULATION,ELEVATION) VALUES('HELLO',3000,100);
INSERT INTO CITIES(NAME,POPULATION,ELEVATION) VALUES('WORLD',4000,110);
INSERT INTO CITIES(NAME,POPULATION,ELEVATION) VALUES('WORLD',5000,110);
INSERT INTO CITIES(NAME,POPULATION,ELEVATION) VALUES('WORLD',6000,110);

INSERT INTO CAPITALS(NAME,POPULATION,ELEVATION,STATE) VALUES('YAMA',3000,120,'AB');
INSERT INTO CAPITALS(NAME,POPULATION,ELEVATION,STATE) VALUES('YAMA',4000,120,'AB');
INSERT INTO CAPITALS(NAME,POPULATION,ELEVATION,STATE) VALUES('YAMA',5000,120,'AB');
INSERT INTO CAPITALS(NAME,POPULATION,ELEVATION,STATE) VALUES('KAWA',4000,130,'CD');
INSERT INTO CAPITALS(NAME,POPULATION,ELEVATION,STATE) VALUES('KAWA',5000,130,'CD');
INSERT INTO CAPITALS(NAME,POPULATION,ELEVATION,STATE) VALUES('KAWA',6000,130,'CD');
INSERT INTO CAPITALS(NAME,POPULATION,ELEVATION,STATE) VALUES('KAWA',7000,130,'CD');

--SELECT NAME,POPULATION,avg(population::numeric)OVER(PARTITION BY NAME) AS AVG FROM CITIES;


SELECT NAME,POPULATION,AVG(POPULATION::NUMERIC) OVER W AS AVG FROM ONLY CITIES
WINDOW W AS (PARTITION BY NAME);

SELECT CAPITALS.NAME,CAPITALS.POPULATION,SUM(CAPITALS.POPULATION::NUMERIC) OVER W AS SUM,AVG(CAPITALS.POPULATION::NUMERIC) OVER W FROM ONLY CAPITALS
WINDOW W AS (PARTITION BY NAME);